/* Verbatim excerpt of 20 entries from KnowYourBlock/Resources/streets.json.
   Generated by scripts/gen_demo_data.py — regenerate, don't hand-edit. */
window.KYB_STREETS = [
  {
    "id": "shirley-chisholm-place",
    "honoraryName": "Shirley Chisholm Place",
    "honoree": "Shirley Chisholm",
    "categories": [
      "Civil Rights & Social Justice",
      "Politics & Public Office"
    ],
    "faceImage": "shirley-chisholm-place_badge",
    "signImage": "sign_plate",
    "neighborhood": "Crown Heights",
    "location": {
      "lat": 40.67289,
      "lng": -73.941984,
      "crossStreets": "Southwest corner of Park Place & Kingston Avenue"
    },
    "story": "Shirley Chisholm grew up mostly in Brooklyn, the daughter of a Barbadian factory worker and a Guyanese seamstress, and she never let anyone forget where she came from or soften what she had to say. She started in Brooklyn's political clubs, then the State Assembly, and in 1968 she became the first Black woman elected to the United States Congress.\n\nHer campaign slogan was \"unbought and unbossed,\" and she meant it literally — she fought her own party as often as the opposition. In 1972 she ran for the Democratic presidential nomination, the first Black candidate and first woman to seek a major party's nod for president, a campaign nobody expected her to win and everybody remembers.\n\nThis corner, at Park Place and Kingston Avenue in Crown Heights, sits in the neighborhood where her political life took root. She served in Congress until 1983, and kept teaching and organizing long after.",
    "links": [
      {
        "label": "Wikipedia: Shirley Chisholm",
        "url": "https://en.wikipedia.org/wiki/Shirley_Chisholm"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetc25c.html?b=BK&letter=S"
      }
    ],
    "yearCoNamed": 2008
  },
  {
    "id": "walt-whitman-way",
    "honoraryName": "Walt Whitman Way",
    "honoree": "Walt Whitman",
    "categories": [
      "Arts, Film & Literature"
    ],
    "faceImage": "walt-whitman-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Fort Greene",
    "location": {
      "lat": 40.689897,
      "lng": -73.964264,
      "crossStreets": "DeKalb Avenue at Ryerson Street"
    },
    "story": "Long before \"Leaves of Grass\" made him one of the most influential poets America ever produced, Walt Whitman was a Brooklyn newspaperman. He edited the Brooklyn Daily Eagle from 1846 to 1848, walking these same Fort Greene streets on his way to and from the print shop, and it was a Brooklyn printer on Cranberry Street who set the type for the first edition of \"Leaves of Grass\" in 1855 — a book Whitman kept revising and expanding for the rest of his life.\n\nWhen the Civil War broke out, Whitman went to Washington to find his wounded brother and ended up staying for years as a volunteer nurse, sitting with soldiers in military hospitals, writing letters home for men who couldn't, and holding the hands of the dying. That experience became \"Drum-Taps,\" his unflinching, tender wartime poetry collection.\n\nHe never stopped writing about Brooklyn as a living, breathing, democratic thing — crowds on the ferry, workers in the street, the sheer noisy fact of everyone existing at once. This stretch of DeKalb Avenue, in the Fort Greene neighborhood where he spent so much of his working life, now carries his name.",
    "links": [
      {
        "label": "Wikipedia: Walt Whitman",
        "url": "https://en.wikipedia.org/wiki/Walt_Whitman"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetc898.html?b=BK&letter=W"
      }
    ],
    "yearCoNamed": 2019
  },
  {
    "id": "elizabeth-jennings-place",
    "honoraryName": "Elizabeth Jennings Place",
    "honoree": "Elizabeth Jennings Graham",
    "categories": [
      "Civil Rights & Social Justice"
    ],
    "faceImage": "elizabeth-jennings-place_badge",
    "signImage": "sign_plate",
    "neighborhood": "Civic Center",
    "location": {
      "lat": 40.711956,
      "lng": -74.006136,
      "crossStreets": "Park Row, between Beekman and Spruce Streets"
    },
    "story": "A century before Rosa Parks refused to give up her seat, Elizabeth Jennings did the same thing on a New York City streetcar. On a Sunday morning in July 1854, on her way to play organ at her church, a conductor tried to force her off a whites-only car near this stretch of Lower Manhattan. She held on to the window frame; he and a police officer eventually threw her to the street.\n\nJennings sued the streetcar company and won, represented in court by a 24-year-old lawyer named Chester A. Arthur — who would become President of the United States three decades later. The verdict led the company, and eventually the whole city, to desegregate its streetcar lines, more than a hundred years before the Montgomery bus boycott made the same fight famous nationwide.\n\nJennings went on to found one of the city's first kindergartens for Black children. This stretch of Park Row, near where she was pulled from the streetcar, has carried her name since 2006.",
    "links": [
      {
        "label": "Wikipedia: Elizabeth Jennings Graham",
        "url": "https://en.wikipedia.org/wiki/Elizabeth_Jennings_Graham"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetba38.html?b=M&letter=E"
      }
    ],
    "yearCoNamed": 2006
  },
  {
    "id": "elizabeth-blackwell-place",
    "honoraryName": "Dr. Elizabeth Blackwell Place",
    "honoree": "Elizabeth Blackwell",
    "categories": [
      "Science & Innovation"
    ],
    "faceImage": "elizabeth-blackwell-place_badge",
    "signImage": "sign_plate",
    "neighborhood": "Financial District",
    "location": {
      "lat": 40.709922,
      "lng": -74.004541,
      "crossStreets": "Gold Street, between Beekman Street and Spruce Street"
    },
    "story": "Elizabeth Blackwell applied to twenty-nine medical schools before Geneva Medical College in upstate New York admitted her in 1847 — the students reportedly voted to accept her application as a joke, then found themselves taught alongside the woman who, in 1849, became the first woman in the United States to earn a medical degree.\n\nNo hospital would let her practice afterward, so in 1857 she and her sister, also a doctor, opened the New York Infirmary for Women and Children in Lower Manhattan, a hospital staffed entirely by women that treated poor patients other institutions turned away and trained the next generation of female physicians the rest of the medical establishment refused to teach.\n\nBlackwell died in 1910 in England, where she'd spent her later career. This stretch of Gold Street in Lower Manhattan has carried her name since 2006.",
    "links": [
      {
        "label": "Wikipedia: Elizabeth Blackwell",
        "url": "https://en.wikipedia.org/wiki/Elizabeth_Blackwell"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreet61ff.html?b=M&letter=D"
      }
    ],
    "yearCoNamed": 2006
  },
  {
    "id": "james-e-davis-avenue",
    "honoraryName": "James E. Davis Avenue",
    "honoree": "James E. Davis",
    "categories": [
      "Public Safety & Military",
      "Politics & Public Office",
      "Civil Rights & Social Justice"
    ],
    "faceImage": "james-e-davis-avenue_badge",
    "signImage": "sign_plate",
    "neighborhood": "Crown Heights",
    "location": {
      "lat": 40.674097,
      "lng": -73.950096,
      "crossStreets": "Nostrand Avenue, between Atlantic Avenue & Eastern Parkway"
    },
    "story": "James E. Davis worked as a Corrections Officer and NYPD Police Officer before entering elected office as a City Council member, and stayed focused on the same cause throughout: stopping violence before it happened. Before he ever held office, he campaigned to pressure Toys \"R\" Us into pulling realistic-looking toy guns from its shelves, and founded Love Yourself, Stop the Violence, an organization aimed directly at young people caught up in the city's cycles of gun violence.\n\nOn July 23, 2003, during a City Council meeting inside City Hall, Davis was shot and killed by a political rival who opened fire without warning in the middle of the session — a stunning act of violence inside the seat of city government, from a man who had spent his career trying to stop exactly that kind of violence in his community.\n\nHe lived from 1962 to 2003. This stretch of Nostrand Avenue, between Atlantic Avenue and Eastern Parkway, now carries his name.",
    "links": [
      {
        "label": "Wikipedia: James E. Davis (New York politician)",
        "url": "https://en.wikipedia.org/wiki/James_E._Davis_(New_York_politician)"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetce11.html?b=BK&letter=J"
      }
    ],
    "yearCoNamed": 2004
  },
  {
    "id": "dorie-miller-place",
    "honoraryName": "Dorie Miller Place",
    "honoree": "Doris \"Dorie\" Miller",
    "categories": [
      "Public Safety & Military",
      "Civil Rights & Social Justice"
    ],
    "faceImage": "dorie-miller-place_badge",
    "signImage": "sign_plate",
    "neighborhood": "East Elmhurst",
    "location": {
      "lat": 40.756,
      "lng": -73.867,
      "crossStreets": "34th Avenue, between 112th Street and 114th Street"
    },
    "story": "Dorie Miller was a Navy messman — one of the only ratings open to Black sailors at the time — aboard the USS West Virginia when Japanese forces attacked Pearl Harbor on December 7, 1941. With no combat training, he carried his mortally wounded captain to safety, then manned an anti-aircraft gun he'd never been taught to operate and fired on the attacking planes until he ran out of ammunition.\n\nHis actions that morning made him one of the first Black heroes of World War II and led to him becoming the first African American awarded the Navy Cross, the Navy's second-highest honor — though it took public pressure from Black newspapers and civil rights organizations to get him properly recognized at all in a still-segregated military.\n\nMiller was killed in action in 1943 when his ship was sunk in the Pacific. This block of 34th Avenue in East Elmhurst has carried his name since 1993.",
    "links": [
      {
        "label": "Wikipedia: Doris Miller",
        "url": "https://en.wikipedia.org/wiki/Doris_Miller"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetc4e8.html?b=Q&letter=D"
      }
    ],
    "yearCoNamed": 1993,
    "needsVerification": true
  },
  {
    "id": "althea-gibson-street",
    "honoraryName": "Althea Gibson Street",
    "honoree": "Althea Gibson",
    "categories": [
      "Sports",
      "Civil Rights & Social Justice"
    ],
    "faceImage": "althea-gibson-street_badge",
    "signImage": "sign_plate",
    "neighborhood": "Harlem",
    "location": {
      "lat": 40.8192,
      "lng": -73.9382,
      "crossStreets": "West 143rd Street, between Adam Clayton Powell Jr. Boulevard and Malcolm X Boulevard"
    },
    "story": "Althea Gibson grew up playing paddle tennis on the streets of Harlem before a local bandleader helped get her onto a real court, and by 1950 she had broken the color line at the U.S. National Championships — a full seven years before Jackie Robinson's counterpart moment would have seemed possible in most other American sports.\n\nIn 1956 she won the French Championships, becoming the first Black player, man or woman, to win a Grand Slam singles title. She followed it with back-to-back wins at both Wimbledon and the U.S. Championships in 1957 and 1958, dominating a sport that had almost entirely excluded players who looked like her. She later became the first Black player on the women's professional golf tour as well.\n\nGibson died in 2003. This block of West 143rd Street, in the Harlem where she first picked up a racket, has carried her name since 2022.",
    "links": [
      {
        "label": "Wikipedia: Althea Gibson",
        "url": "https://en.wikipedia.org/wiki/Althea_Gibson"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreet75f6.html?b=M&letter=A"
      }
    ],
    "yearCoNamed": 2022,
    "needsVerification": true
  },
  {
    "id": "emily-warren-roebling-way",
    "honoraryName": "Emily Warren Roebling Way",
    "honoree": "Emily Warren Roebling",
    "categories": [
      "Science & Innovation"
    ],
    "faceImage": "emily-warren-roebling-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Brooklyn Heights",
    "location": {
      "lat": 40.699338,
      "lng": -73.995849,
      "crossStreets": "Columbia Heights, between Pineapple & Orange Streets"
    },
    "story": "The Brooklyn Bridge is usually credited to the Roebling family's engineers, but the person who actually kept it moving for its final thirteen years of construction was Emily Warren Roebling. Her father-in-law, John A. Roebling, designed the bridge and died from an injury sustained while surveying its route in 1869. Her husband, Washington Roebling, took over as chief engineer — and then developed decompression sickness from repeated trips into the underwater caissons, leaving him largely bedridden and unable to visit the site for the rest of the project.\n\nEmily became his eyes, hands, and voice. She taught herself the engineering she needed — cable construction, stress analysis, materials strength — and spent over a decade relaying his instructions to the crew, managing contractors, and handling the project's endless political fights at City Hall, all while functioning, in practice, as the bridge's chief engineer in everything but title.\n\nWhen the Brooklyn Bridge finally opened on May 24, 1883, Emily Warren Roebling was given the honor of being the first person to cross it, riding over in a carriage with a rooster on her lap as a symbol of victory. This stretch of Columbia Heights, in the Brooklyn Heights neighborhood where the bridge still lands today, now carries her name.",
    "links": [
      {
        "label": "Wikipedia: Emily Warren Roebling",
        "url": "https://en.wikipedia.org/wiki/Emily_Warren_Roebling"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreet2a61.html?b=BK&letter=E"
      }
    ],
    "yearCoNamed": 2017
  },
  {
    "id": "rena-kanokogi-way",
    "honoraryName": "Rena “Rusty” Kanokogi Way",
    "honoree": "Rena “Rusty” Kanokogi",
    "categories": [
      "Sports",
      "Civil Rights & Social Justice"
    ],
    "faceImage": "rena-kanokogi-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Coney Island",
    "location": {
      "lat": 40.575395,
      "lng": -73.984536,
      "crossStreets": "West 17th Street at Surf Avenue"
    },
    "story": "Rena Kanokogi grew up in Coney Island and started training in judo in 1955, at a time when almost no dojo would take a woman seriously as a competitor. In 1959 she entered a men's YMCA judo championship as part of a men's team and helped it win — and was then asked to give the medal back once officials realized she wasn't a man. She handed it over, and spent the rest of her life making sure no woman after her would have to.\n\nShe traveled to Tokyo to train at the Kodokan, judo's spiritual home, becoming one of the first Western women given serious instruction there. In 1980, she mortgaged her own house to help organize and fund the first Women's World Judo Championship at Madison Square Garden, then spent years lobbying the International Olympic Committee until women's judo was finally added to the Olympic program, debuting as a demonstration sport in 1988 and a full medal event in 1992.\n\nJapan awarded her the Order of the Rising Sun, one of its highest honors for a foreign national, and in 1991 she was inducted into the International Women's Sports Hall of Fame. This corner of West 17th Street and Surf Avenue, in the Coney Island neighborhood where she grew up, now carries her name.",
    "links": [
      {
        "label": "Wikipedia: Rusty Kanokogi",
        "url": "https://en.wikipedia.org/wiki/Rusty_Kanokogi"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetdc17.html?b=BK&letter=R"
      }
    ],
    "yearCoNamed": 2019
  },
  {
    "id": "christopher-wallace-way",
    "honoraryName": "Christopher \"Notorious B.I.G.\" Wallace Way",
    "honoree": "Christopher Wallace (The Notorious B.I.G.)",
    "categories": [
      "Music"
    ],
    "media": {
      "youtubeId": "_JZom_gVfuw",
      "songTitle": "Juicy (Official Video)",
      "youtubeChannel": "The Notorious B.I.G."
    },
    "faceImage": "christopher-wallace-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Clinton Hill",
    "location": {
      "lat": 40.683745,
      "lng": -73.963845,
      "crossStreets": "St. James Place, between Fulton Street & Gates Avenue"
    },
    "story": "Before he was the Notorious B.I.G., Christopher Wallace was a kid on St. James Place, a few doors from Fulton Street, sharp enough to skip two grades and restless enough to leave school anyway. He started rapping on the corner and on cassette tapes that made their way, hand to hand, until one landed with a young A&R named Sean \"Puffy\" Combs.\n\nWhat came next moved fast: Bad Boy Records, the album \"Ready to Die,\" a voice so unmistakable it changed what a New York rap record could sound like. He rhymed about this block in specific, loving, unglamorous detail — the corner store, the elevators that didn't work, the particular ache of wanting more than the block could give you.\n\nHe was killed in Los Angeles in March 1997, sixteen days before his second album, \"Life After Death,\" was released. In 2019, the city made it official: this stretch of St. James Place carries his name, so that anyone walking from Fulton to Gates walks past where Biggie's story actually started.",
    "links": [
      {
        "label": "Wikipedia: The Notorious B.I.G.",
        "url": "https://en.wikipedia.org/wiki/The_Notorious_B.I.G."
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreet1c53.html?b=BK&letter=C"
      }
    ],
    "yearCoNamed": 2019
  },
  {
    "id": "harriet-tubman-avenue",
    "honoraryName": "Harriet Ross Tubman Avenue",
    "honoree": "Harriet Tubman",
    "categories": [
      "Civil Rights & Social Justice"
    ],
    "faceImage": "harriet-tubman-avenue_badge",
    "signImage": "sign_plate",
    "neighborhood": "Bedford-Stuyvesant",
    "location": {
      "lat": 40.681859,
      "lng": -73.932688,
      "crossStreets": "Fulton Street, between Boerum Place & Rockaway Boulevard (a multi-mile stretch — this pin marks a central point near Nostrand Avenue)"
    },
    "story": "Harriet Ross escaped slavery in Maryland in 1849 and went back, again and again, to lead others out along the Underground Railroad — by her own count, and legend's, close to twenty trips and hundreds of people freed. During the Civil War she scouted for the Union Army and helped lead an armed raid that freed more than seven hundred enslaved people, becoming the first woman in U.S. history to lead a military operation of that scale.\n\nLater in life she settled in Auburn, New York, and kept working: buying land for a home for elderly and sick Black residents, eventually giving that land to the African Methodist Episcopal Zion Church, which built the home in 1908. She lived out her last years there.\n\nBrooklyn honors her along a long, central artery: this stretch of Fulton Street, running from Boerum Place out toward Rockaway Boulevard, carries her name — Harriet Ross Tubman Avenue — cutting straight through the heart of the borough she never lived in but whose history she shaped anyway.",
    "links": [
      {
        "label": "Wikipedia: Harriet Tubman",
        "url": "https://en.wikipedia.org/wiki/Harriet_Tubman"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreet40b2.html?b=BK&letter=H"
      }
    ],
    "yearCoNamed": 2004
  },
  {
    "id": "sylvia-rivera-way",
    "honoraryName": "Sylvia Rivera Way",
    "honoree": "Sylvia Rivera",
    "categories": [
      "Civil Rights & Social Justice"
    ],
    "faceImage": "sylvia-rivera-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Greenwich Village",
    "location": {
      "lat": 40.733156,
      "lng": -74.006229,
      "crossStreets": "Northeast corner of Hudson Street and Christopher Street"
    },
    "story": "Sylvia Rivera was present at the Stonewall Inn, a few blocks from this corner, on the night in 1969 that the uprising against a police raid there helped ignite the modern LGBTQ rights movement. A trans woman of Puerto Rican and Venezuelan descent who had been surviving on these streets since her early teens, she spent the rest of her life fighting to make sure that movement didn't leave trans people behind.\n\nWith her close friend Marsha P. Johnson, Rivera co-founded S.T.A.R. (Street Transvestite Action Revolutionaries) in 1970, opening a shelter for homeless queer and trans youth in the East Village at a time almost no one else would. She spent decades pushing, often against resistance from within the gay rights movement itself, for trans people to be included in the fight rather than used as its most disposable members.\n\nRivera died in 2002. This corner of Hudson and Christopher Streets, in the neighborhood where the movement she gave her life to began, has carried her name since 2005.",
    "links": [
      {
        "label": "Wikipedia: Sylvia Rivera",
        "url": "https://en.wikipedia.org/wiki/Sylvia_Rivera"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetb588.html?b=M&letter=S"
      }
    ],
    "yearCoNamed": 2005
  },
  {
    "id": "frances-perkins-place",
    "honoraryName": "Frances Perkins Place",
    "honoree": "Frances Perkins",
    "categories": [
      "Politics & Public Office"
    ],
    "faceImage": "frances-perkins-place_badge",
    "signImage": "sign_plate",
    "neighborhood": "Hell's Kitchen",
    "location": {
      "lat": 40.7617,
      "lng": -73.9922,
      "crossStreets": "West 46th Street, between Ninth Avenue and Tenth Avenue"
    },
    "story": "Frances Perkins was in Washington Square Park in 1911 when the Triangle Shirtwaist Factory caught fire nearby, and she watched garment workers, mostly young immigrant women, jump to their deaths rather than burn. The horror of that afternoon shaped the rest of her career in public service.\n\nIn 1933 Franklin Roosevelt named her Secretary of Labor, making her the first woman to serve in a presidential Cabinet in American history. Over the next twelve years — she stayed through all four of FDR's terms, longer than any Labor Secretary before or since — she helped design Social Security, the federal minimum wage, unemployment insurance, and the 40-hour work week, building much of the basic architecture of the American social safety net still in place today.\n\nPerkins died in 1965. This block of West 46th Street has carried her name since 2022.",
    "links": [
      {
        "label": "Wikipedia: Frances Perkins",
        "url": "https://en.wikipedia.org/wiki/Frances_Perkins"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetea2c.html?b=M&letter=F"
      }
    ],
    "yearCoNamed": 2022,
    "needsVerification": true
  },
  {
    "id": "raoul-wallenberg-way",
    "honoraryName": "Raoul Wallenberg Way",
    "honoree": "Raoul Wallenberg",
    "categories": [
      "Civil Rights & Social Justice",
      "Politics & Public Office"
    ],
    "faceImage": "raoul-wallenberg-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Borough Park",
    "location": {
      "lat": 40.635449,
      "lng": -73.991688,
      "crossStreets": "13th Avenue, between 36th & 60th Streets"
    },
    "story": "Raoul Wallenberg was a Swedish diplomat posted to Budapest in 1944, at the exact moment the Nazi occupation of Hungary was accelerating the deportation of its Jewish population to death camps. Using his diplomatic position, he issued protective passports and set up safe houses under Swedish protection, credited with saving tens of thousands of Hungarian Jews in a matter of months, at direct personal risk the entire time.\n\nWhen Soviet forces liberated Budapest in January 1945, Wallenberg presented himself to Soviet military authorities — and then vanished. The Soviet Union eventually acknowledged he had died in their custody, though the full circumstances were never fully resolved. He remains one of the most honored rescuers of the Holocaust, commemorated by memorials across the world.\n\nThis stretch of 13th Avenue, between 36th and 60th Streets in Borough Park — home to one of the largest Orthodox Jewish communities in the United States — now carries his name.",
    "links": [
      {
        "label": "Wikipedia: Raoul Wallenberg",
        "url": "https://en.wikipedia.org/wiki/Raoul_Wallenberg"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetdc17.html?b=BK&letter=R"
      }
    ],
    "yearCoNamed": 2012
  },
  {
    "id": "margaret-corbin-way",
    "honoraryName": "Margaret Corbin Way",
    "honoree": "Margaret Corbin",
    "categories": [
      "Public Safety & Military",
      "Civil Rights & Social Justice"
    ],
    "faceImage": "margaret-corbin-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Brighton Beach",
    "location": {
      "lat": 40.57841,
      "lng": -73.954236,
      "crossStreets": "Corbin Place, between Cass Place & the Boardwalk"
    },
    "story": "Margaret Corbin followed her husband John into the Revolutionary War, accompanying him to his post manning a small cannon on a ridge that would later be named Fort Tryon. In November 1776, Hessian forces attacked the position and killed him at his gun — and rather than retreat, Corbin took over loading and firing the cannon herself until she too was hit, taking wounds that left her permanently disabled for the rest of her life.\n\nIn 1779, Congress made her the first woman in American history to receive a military pension from the new nation, formal recognition that a woman had fought and been wounded in combat for it. She was later buried at West Point with full military honors.\n\nThis stretch of Corbin Place, between Cass Place and the Boardwalk in Brighton Beach, now carries her name.",
    "links": [
      {
        "label": "Wikipedia: Margaret Corbin",
        "url": "https://en.wikipedia.org/wiki/Margaret_Corbin"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetbae0.html?b=BK&letter=M"
      }
    ],
    "yearCoNamed": 2017
  },
  {
    "id": "louis-armstrong-place",
    "honoraryName": "Louis Armstrong Place",
    "honoree": "Louis Armstrong",
    "categories": [
      "Music"
    ],
    "media": {
      "youtubeId": "rBrd_3VMC3c",
      "songTitle": "What a Wonderful World (Official Video)",
      "youtubeChannel": "LouisArmstrongVEVO"
    },
    "faceImage": "louis-armstrong-place_badge",
    "signImage": "sign_plate",
    "neighborhood": "Corona",
    "location": {
      "lat": 40.756238,
      "lng": -73.861621,
      "crossStreets": "107th Street, between 37th Avenue and Northern Boulevard"
    },
    "story": "Louis Armstrong bought the house on this block of 107th Street in 1943 and lived there for the rest of his life, even at the height of a fame that would have let him live almost anywhere in the world. He'd already reinvented American music once, in 1920s Chicago and New York, turning jazz from a collective ensemble music into a showcase for the virtuoso soloist, his trumpet and his gravelly voice equally unmistakable.\n\nFrom this modest Corona house, he kept touring and recording almost until his death, entertaining heads of state and royalty abroad and, back home, the neighborhood kids who'd gather on the stoop to hear him practice. His 1964 recording of “Hello, Dolly!” knocked the Beatles off the top of the charts, an unlikely late-career hit from a man who by then had been famous for four decades.\n\nArmstrong died in 1971, in the house on this block. It's preserved today as the Louis Armstrong House Museum, and this stretch of 107th Street has carried his name since 2003.",
    "links": [
      {
        "label": "Wikipedia: Louis Armstrong",
        "url": "https://en.wikipedia.org/wiki/Louis_Armstrong"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetff39.html?b=Q&letter=L"
      }
    ],
    "yearCoNamed": 2003
  },
  {
    "id": "tenzing-norgay-sherpa-way",
    "honoraryName": "Tenzing Norgay Sherpa Way",
    "honoree": "Tenzing Norgay",
    "categories": [
      "Sports",
      "Community & Local Heroes"
    ],
    "faceImage": "tenzing-norgay-sherpa-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Elmhurst",
    "location": {
      "lat": 40.7469,
      "lng": -73.8907,
      "crossStreets": "75th Street, between Broadway and Woodside Avenue"
    },
    "story": "Tenzing Norgay was, alongside Sir Edmund Hillary, one of the first two people ever confirmed to reach the summit of Mount Everest, on May 29, 1953 — a feat that made him, as a Sherpa from the Himalayan region straddling Nepal and Tibet, one of the most famous mountaineers in the world at a time when the guides who made such expeditions possible rarely received equal credit.\n\nTIME magazine later named him one of the hundred most influential people of the 20th century. This stretch of 75th Street runs through Elmhurst and Jackson Heights, home to one of the largest concentrations of Nepali and Sherpa immigrants in the United States, a community that has grown substantially in New York over the past two decades.\n\nNorgay died in 1986. This block, in the neighborhood his community has built a home in, has carried his name since 2022.",
    "links": [
      {
        "label": "Wikipedia: Tenzing Norgay",
        "url": "https://en.wikipedia.org/wiki/Tenzing_Norgay"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetd0e5.html?b=Q&letter=T"
      }
    ],
    "yearCoNamed": 2022,
    "needsVerification": true
  },
  {
    "id": "susannah-mushatt-jones-avenue",
    "honoraryName": "Susannah Mushatt Jones Avenue",
    "honoree": "Susannah Mushatt Jones",
    "categories": [
      "Community & Local Heroes"
    ],
    "faceImage": "susannah-mushatt-jones-avenue_badge",
    "signImage": "sign_plate",
    "neighborhood": "Starrett City",
    "location": {
      "lat": 40.6492,
      "lng": -73.88767,
      "crossStreets": "Vandalia Avenue at Louisiana Avenue"
    },
    "story": "Susannah Mushatt Jones was born in Alabama in 1899 and graduated from the Calhoun Boarding School, founded by Booker T. Washington, before relocating to New York and settling into a long, active life in East New York's Vandalia Senior Housing. She served on its Tenant Patrol for more than 21 years, staying on the tenant board until she was 100 years old.\n\nBy the time she died in 2016, she had quietly become something extraordinary: the world's oldest verified living person, and the last known American verified to have been born before 1900 — a direct link to the 19th century who lived to see the 21st.\n\nThis intersection of Vandalia Avenue and Louisiana Avenue, in the housing community she served for over two decades, now carries her name.",
    "links": [
      {
        "label": "Wikipedia: Susannah Mushatt Jones",
        "url": "https://en.wikipedia.org/wiki/Susannah_Mushatt_Jones"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreetc25c.html?b=BK&letter=S"
      }
    ],
    "yearCoNamed": 2017
  },
  {
    "id": "celia-cruz-boulevard",
    "honoraryName": "Celia Cruz Boulevard",
    "honoree": "Celia Cruz",
    "categories": [
      "Music"
    ],
    "media": {
      "youtubeId": "imeXSRNRMeg",
      "songTitle": "La Negra Tiene Tumbao (Official Video)",
      "youtubeChannel": "CeliaCruzVEVO"
    },
    "faceImage": "celia-cruz-boulevard_badge",
    "signImage": "sign_plate",
    "neighborhood": "Fordham",
    "location": {
      "lat": 40.861868,
      "lng": -73.89229,
      "crossStreets": "Fordham Road, between Third Avenue and Jerome Avenue"
    },
    "story": "Celia Cruz was already a star in Cuba, singing with the country's most popular orchestra, when the 1959 revolution led her to leave for good, settling eventually in New York. She built a second career here even bigger than her first, becoming the single most influential female voice in salsa music and earning the title the world came to know her by: the Queen of Salsa.\n\nShe recorded steadily for five decades, her booming contralto and improvised “¡Azúcar!” exclamation becoming as recognizable as any voice in Latin music, and she never stopped singing exclusively in Spanish even as she crossed over into mainstream American fame. She won multiple Grammy Awards and a National Medal of Arts along the way.\n\nCruz died in 2003, the same year this stretch of Fordham Road — in a neighborhood home to one of the city's largest Latino communities — was named for her.",
    "links": [
      {
        "label": "Wikipedia: Celia Cruz",
        "url": "https://en.wikipedia.org/wiki/Celia_Cruz"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreet1060.html?b=BX&letter=C"
      }
    ],
    "yearCoNamed": 2003
  },
  {
    "id": "granville-t-woods-way",
    "honoraryName": "Granville T. Woods Way",
    "honoree": "Granville T. Woods",
    "categories": [
      "Science & Innovation"
    ],
    "faceImage": "granville-t-woods-way_badge",
    "signImage": "sign_plate",
    "neighborhood": "Coney Island",
    "location": {
      "lat": 40.57699,
      "lng": -73.981565,
      "crossStreets": "Stillwell Avenue at Mermaid Avenue"
    },
    "story": "Granville T. Woods held more than 50 patents over his career and was so prolific and so often challenged by rivals claiming his ideas as their own that he became known as \"Black Edison.\" His most consequential invention barely gets mentioned outside engineering circles: the third rail, the simple but essential system that lets subway trains draw electric power from a track instead of overhead wires — without it, the New York City subway as it actually exists wouldn't work the way it does.\n\nHe had a lighter side too. His electrical figure-eight amusement apparatus, patented for early amusement parks, helped lay the groundwork for the modern roller coaster — meaning generations of Coney Island visitors have Woods to thank for more than just their commute.\n\nHe lived from 1856 to 1910. This corner of Stillwell and Mermaid Avenues, in the Coney Island his invention helped entertain for a century, now carries his name.",
    "links": [
      {
        "label": "Wikipedia: Granville Woods",
        "url": "https://en.wikipedia.org/wiki/Granville_Woods"
      },
      {
        "label": "NYC Honorary Street Names (source)",
        "url": "https://www.nycstreets.info/honorStreet68ca.html?b=BK&letter=G"
      }
    ],
    "yearCoNamed": 2007
  }
];
